name: Test Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 17.0.2
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: ./gradlew --stacktrace --info
      
      
    - name: Upload windows builds
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v2
      with:
        name: MZmine_windows_msi_installer
        path: build/jpackage/*.msi
        retention-days: 7  # store for 7 days
      
    - name: Upload windows portable builds
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v2
      with:
        name: MZmine_windows_msi_installer
        path: build/jpackage/MZmine/
        retention-days: 7  # store for 7 days
        
    - name: Upload builds ubuntu deb
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v2
      with:
        name: MZmine_linux_deb_package
        path: build/jpackage/*.deb
        retention-days: 7  # store for 7 days
        
    - name: Upload builds ubuntu rpm
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v2
      with:
        name: MZmine_linux_rpm_package
        path: build/jpackage/*.rpm
        retention-days: 7  # store for 7 days
        
    - name: Upload builds macos
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v2
      with:
        name: MZmine_macos_dmg_installer
        path: build/jpackage/*.dmg
        retention-days: 7  # store for 7 days
