name: Publish MZmine release

on: workflow_dispatch
    
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 17.0.2
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: ./gradlew --stacktrace --info
      # run: ./gradlew incrementPatch
       
    - name: Update Automatic Release Ubuntu
      if: matrix.os == 'ubuntu-latest'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN}}"
        automatic_release_tag: "v3.0.0-beta"
        prerelease: true
        title: "MZmine 3.0.0-beta"
        files: |
          build/jpackage/*.deb
          build/jpackage/*.rpm

    - name: Zip portable windows
      if: matrix.os == 'windows-latest'
      uses: papeloto/action-zip@v1
      with:
        files: build/jpackage/MZmine/
        dest: build/jpackage/MZmine_windows_portable.zip

    - name: Update Automatic Release Window
      if: matrix.os == 'windows-latest'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN}}"
        automatic_release_tag: "v3.0.0-beta"
        prerelease: true
        title: "MZmine 3.0.0-beta"
        files: |
          build/jpackage/*.msi
          build/jpackage/MZmine_windows_portable.zip


    - name: Update Automatic Release MacOS
      if: matrix.os == 'macos-latest'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN}}"
        automatic_release_tag: "v3.0.0-beta"
        prerelease: true
        title: "MZmine 3.0.0-beta"
        files: build/jpackage/*.dmg
