name: test secrets

on: workflow_dispatch

jobs:
    mysecs:
        environment: MZMINE
        runs-on: ubuntu-latest
        env:
            TESTRUNNER_USER: ${{ secrets.TESTRUNNER }}
            TESTRUNNER_ACTION: ${{ secrets.TESTRUNNER_USER }}
            TRDIRECT: "Ic5OXgAAAJwAAAABAAAAEAAAAIBsaWNlbnNlU2lnbmF0dXJlVohMd37EeO/qfpUE7X+58mOWQlIC71H3IycHAVqw2vx+iWt32HYydQh9vNaHs1fndn1pEFQGyRhNWDv59+4lF7/HCaKykejdgU2KrR2MEC2wjgmGkPiSi6t21/UenjcJjkkRIad3CLvIK8gSEqx+QapshJ4363rOGIu4bfTGEj4AAAAeAAAAAgAAAAgAAAAKbmlja25hbWV0ZXN0cnVubmVyAAAAHgAAAAsAAAAOcHJvX3VudGlsX2RhdGUAAAgJRBvLAAAAABQAAAACAAAACAAAAABzZXJ2aWNlcwAAACIAAAACAAAADwAAAAdzaWduYXR1cmVEaWdlc3RTSEEtNTEyAAAAJAAAAAsAAAAUdHJpYWxfcHJvX3VudGlsX2RhdGUAAAGPI0nzAA=="
            TESTRUNNER_VAR: ${{ vars.TESTRUNNER_VAR }}
            TEST_SEC: ${{ secrets.TEST_SEC }}
            ENVUSER_BASE64: ${{ secrets.ENVUSER_BASE64 }}
            USER_BASE64: ${{ secrets.USER_BASE64 }} 
            TRINDIRECT: $TEST_USER
        steps:
            - uses: actions/checkout@v4

            - name: log
              run: |
                echo ${{ secrets.TESTRUNNER_USER }} | sed 's/./& /g'
                echo $TESTRUNNER_USER | sed 's/./& /g'
                echo ${{ secrets.TESTRUNNER }} | sed 's/./& /g'
                echo $TESTRUNNER_VAR | sed 's/./& /g'


            - name: Create TESTRUNNER user file 
              run: |
                mkdir -p $HOME/.mzmine/users/
                echo $HOME/.mzmine/users/
                echo "$TEST_USER" > $HOME/.mzmine/users/testrunner.mzuserstr
                echo $ENVUSER_BASE64 | base64 --decode > $HOME/.mzmine/users/envuser.mzuserstr
                echo $USER_BASE64 | base64 --decode > $HOME/.mzmine/users/user_base64.mzuserstr
            
